# Generated by Django 5.2.5 on 2025-08-18 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_companyinvitation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyInvitation',
        ),
    ]
