# Generated by Django 5.2.5 on 2025-08-17 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('block', models.IntegerField()),
                ('unit', models.IntegerField()),
                ('chicken_samoosa_quantity', models.IntegerField()),
                ('mince_samoosa_quantity', models.IntegerField()),
                ('koeksister_quantity', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
